/**
 * Scan command copy and reusable UI text.
 */

export const scanCommandPrompts = {
  scanBanner: '🔒 Security Scan',
  scanFilePrefix: (target: string) => `🔒 Scanning file: ${target}`,
  scanSkillPrefix: (skill: string) => `🔒 Scanning skill: ${skill}`,
  scanAnalysisTitle: '🤖 SA Agent Security Analysis',
  scanConnecting: 'Connecting to SA Agent model...',
  scanConnected: 'SA Agent is scanning...',
  scanFallback: 'SA Agent deep analysis unavailable, fallback to basic scan.',
  scanComplete: 'SA Agent analysis complete!',
  autoRepairTitle: '🔧 Auto Repair Summary',
  autoRepairSkipped: '⚠️ Auto repair skipped: no writable local source file resolved.',
  autoRepairNoPatch: '⚠️ No line-based high-risk findings to patch automatically.',
  repairTextModeWarning: '⚠️ `--repair` currently supports text mode only. Switching to text output.',
  applyWithoutRepairWarning: '⚠️ `--apply` is ignored without `--repair`.',
  nextSteps: '📌 Next Steps:',
  suggestions: '📌 Suggestions:',
  importHint: (target: string) => `   sa import ${target}    # Import this skill`,
  scanListHint: '   sa scan                   # View scannable skills',
  scanJsonHint: (target: string) => `   sa scan ${target} -f json   # Export machine-readable findings`,
  scanRepairHint: (target: string) => `   sa scan ${target} --repair  # Generate repaired copy and rescan`,
  viewInfoHint: (target: string) => `   sa info ${target}            # Check source/version before remediation`,
  fixSkillHint: '   # Fix high-risk lines in SKILL.md, then rerun this scan',
  patchPromptHint: '   # Patch risky commands/prompts, then rerun this scan',
  importFirstHint: '   sa import <skill>        # Import a skill first',
  installOfficialHint: '   npx skills add <owner/repo> --skill <name>  # Install via official CLI',
  viewScannableHint: '   sa scan                   # View scannable skills',
  viewSkillHint: (skill: string) => `   sa scan ${skill}     # Scan imported skill`,
  viewFileHint: '   sa scan <file-path>      # Scan local file',
  examplesHeader: 'Examples:',
  exampleScanSkill: '   sa scan frontend-design',
  exampleScanFile: '   sa scan ./my-skill/SKILL.md',
  exampleScanJson: '   sa scan skill.json -f json',
  exampleRepair: '   sa scan frontend-design --repair',
  fileNotFound: (target: string) => `❌ Skill not found: ${target}`,
  cannotFetchContent: '❌ Could not fetch skill content for scanning',
  remoteInstallTip: '   \u{1F4A1} Tip: Remote skills need to be installed via official CLI first.',
  remoteOpenClawTip: '   # Or scan local OpenClaw skills',
  repairMode: (applied: boolean) => `   Mode: ${applied ? 'applied to original' : 'saved as copy'}`,
};
